/*
              __ __ __
             |__|__|  | __
             |  |  |  ||__|
  ___ ___ __ |  |  |  |
 |   |   |  ||  |  |  |    Ubiquitous Internet @ IIT-CNR
 |   |   |  ||  |  |  |    C++ quantum routing libraries and tools
 |_______|__||__|__|__|    https://github.com/ccicconetti/quantum-routing

Licensed under the MIT License <http://opensource.org/licenses/MIT>
Copyright (c) 2022 C. Cicconetti <https://ccicconetti.github.io/>

Permission is hereby  granted, free of charge, to any  person obtaining a copy
of this software and associated  documentation files (the "Software"), to deal
in the Software  without restriction, including without  limitation the rights
to  use, copy,  modify, merge,  publish, distribute,  sublicense, and/or  sell
copies  of  the Software,  and  to  permit persons  to  whom  the Software  is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE  IS PROVIDED "AS  IS", WITHOUT WARRANTY  OF ANY KIND,  EXPRESS OR
IMPLIED,  INCLUDING BUT  NOT  LIMITED TO  THE  WARRANTIES OF  MERCHANTABILITY,
FITNESS FOR  A PARTICULAR PURPOSE AND  NONINFRINGEMENT. IN NO EVENT  SHALL THE
AUTHORS  OR COPYRIGHT  HOLDERS  BE  LIABLE FOR  ANY  CLAIM,  DAMAGES OR  OTHER
LIABILITY, WHETHER IN AN ACTION OF  CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE  OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "examplenetwork.h"

namespace uiiit {
namespace qr {

// downloaded from http://www.topology-zoo.org/files/Garr201201.graphml
std::string exampleNetwork() {
  // clang-format off
  return
  "<?xml version=\"1.0\" encoding=\"utf-8\"?><graphml xmlns=\"http://graphml.graphdrawing.org/xmlns\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd\">\n"
"  <key attr.name=\"description\" attr.type=\"string\" for=\"edge\" id=\"d42\" />\n"
"  <key attr.name=\"label\" attr.type=\"string\" for=\"edge\" id=\"d41\" />\n"
"  <key attr.name=\"id\" attr.type=\"string\" for=\"edge\" id=\"d40\" />\n"
"  <key attr.name=\"key\" attr.type=\"int\" for=\"edge\" id=\"d39\" />\n"
"  <key attr.name=\"LinkSpeedRaw\" attr.type=\"double\" for=\"edge\" id=\"d38\" />\n"
"  <key attr.name=\"LinkNote\" attr.type=\"string\" for=\"edge\" id=\"d37\" />\n"
"  <key attr.name=\"LinkLabel\" attr.type=\"string\" for=\"edge\" id=\"d36\" />\n"
"  <key attr.name=\"LinkSpeedUnits\" attr.type=\"string\" for=\"edge\" id=\"d35\" />\n"
"  <key attr.name=\"LinkSpeed\" attr.type=\"string\" for=\"edge\" id=\"d34\" />\n"
"  <key attr.name=\"Longitude\" attr.type=\"double\" for=\"node\" id=\"d33\" />\n"
"  <key attr.name=\"Country\" attr.type=\"string\" for=\"node\" id=\"d32\" />\n"
"  <key attr.name=\"Latitude\" attr.type=\"double\" for=\"node\" id=\"d31\" />\n"
"  <key attr.name=\"label\" attr.type=\"string\" for=\"node\" id=\"d30\" />\n"
"  <key attr.name=\"id\" attr.type=\"int\" for=\"node\" id=\"d29\" />\n"
"  <key attr.name=\"Internal\" attr.type=\"int\" for=\"node\" id=\"d28\" />\n"
"  <key attr.name=\"Testbed\" attr.type=\"int\" for=\"graph\" id=\"d27\" />\n"
"  <key attr.name=\"LastProcessed\" attr.type=\"string\" for=\"graph\" id=\"d26\" />\n"
"  <key attr.name=\"DateYear\" attr.type=\"string\" for=\"graph\" id=\"d25\" />\n"
"  <key attr.name=\"NetworkDate\" attr.type=\"string\" for=\"graph\" id=\"d24\" />\n"
"  <key attr.name=\"Transit\" attr.type=\"int\" for=\"graph\" id=\"d23\" />\n"
"  <key attr.name=\"Developed\" attr.type=\"int\" for=\"graph\" id=\"d22\" />\n"
"  <key attr.name=\"Creator\" attr.type=\"string\" for=\"graph\" id=\"d21\" />\n"
"  <key attr.name=\"Layer\" attr.type=\"string\" for=\"graph\" id=\"d20\" />\n"
"  <key attr.name=\"LastAccess\" attr.type=\"string\" for=\"graph\" id=\"d19\" />\n"
"  <key attr.name=\"DateMonth\" attr.type=\"string\" for=\"graph\" id=\"d18\" />\n"
"  <key attr.name=\"DateModifier\" attr.type=\"string\" for=\"graph\" id=\"d17\" />\n"
"  <key attr.name=\"SourceGitVersion\" attr.type=\"string\" for=\"graph\" id=\"d16\" />\n"
"  <key attr.name=\"IX\" attr.type=\"int\" for=\"graph\" id=\"d15\" />\n"
"  <key attr.name=\"Customer\" attr.type=\"int\" for=\"graph\" id=\"d14\" />\n"
"  <key attr.name=\"ToolsetVersion\" attr.type=\"string\" for=\"graph\" id=\"d13\" />\n"
"  <key attr.name=\"label\" attr.type=\"string\" for=\"graph\" id=\"d12\" />\n"
"  <key attr.name=\"Commercial\" attr.type=\"int\" for=\"graph\" id=\"d11\" />\n"
"  <key attr.name=\"Backbone\" attr.type=\"int\" for=\"graph\" id=\"d10\" />\n"
"  <key attr.name=\"Type\" attr.type=\"string\" for=\"graph\" id=\"d9\" />\n"
"  <key attr.name=\"DateType\" attr.type=\"string\" for=\"graph\" id=\"d8\" />\n"
"  <key attr.name=\"Version\" attr.type=\"string\" for=\"graph\" id=\"d7\" />\n"
"  <key attr.name=\"Source\" attr.type=\"string\" for=\"graph\" id=\"d6\" />\n"
"  <key attr.name=\"Access\" attr.type=\"int\" for=\"graph\" id=\"d5\" />\n"
"  <key attr.name=\"Provenance\" attr.type=\"string\" for=\"graph\" id=\"d4\" />\n"
"  <key attr.name=\"Network\" attr.type=\"string\" for=\"graph\" id=\"d3\" />\n"
"  <key attr.name=\"GeoExtent\" attr.type=\"string\" for=\"graph\" id=\"d2\" />\n"
"  <key attr.name=\"GeoLocation\" attr.type=\"string\" for=\"graph\" id=\"d1\" />\n"
"  <key attr.name=\"DateObtained\" attr.type=\"string\" for=\"graph\" id=\"d0\" />\n"
"  <graph edgedefault=\"undirected\">\n"
"    <data key=\"d0\">28/03/12</data>\n"
"    <data key=\"d1\">Italy</data>\n"
"    <data key=\"d2\">Country</data>\n"
"    <data key=\"d3\">GARR</data>\n"
"    <data key=\"d4\">Primary</data>\n"
"    <data key=\"d5\">0</data>\n"
"    <data key=\"d6\">http://www.garr.it/images/stories/mappe/mappa201111.jpg</data>\n"
"    <data key=\"d7\">1.0</data>\n"
"    <data key=\"d8\">Historic</data>\n"
"    <data key=\"d9\">REN</data>\n"
"    <data key=\"d10\">1</data>\n"
"    <data key=\"d11\">0</data>\n"
"    <data key=\"d12\">Garr201201</data>\n"
"    <data key=\"d13\">0.3.34dev-20120328</data>\n"
"    <data key=\"d14\">0</data>\n"
"    <data key=\"d15\">0</data>\n"
"    <data key=\"d16\">e278b1b</data>\n"
"    <data key=\"d17\">=</data>\n"
"    <data key=\"d18\">11</data>\n"
"    <data key=\"d19\">28/03/12</data>\n"
"    <data key=\"d20\">IP</data>\n"
"    <data key=\"d21\">Topology Zoo Toolset</data>\n"
"    <data key=\"d22\">1</data>\n"
"    <data key=\"d23\">1</data>\n"
"    <data key=\"d24\">2011_11</data>\n"
"    <data key=\"d25\">2011</data>\n"
"    <data key=\"d26\">2012_03_28</data>\n"
"    <data key=\"d27\">0</data>\n"
"    <node id=\"0\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">0</data>\n"
"      <data key=\"d30\">Svizzera</data>\n"
"    </node>\n"
"    <node id=\"1\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">39.20738</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">1</data>\n"
"      <data key=\"d33\">9.13462</data>\n"
"      <data key=\"d30\">CA</data>\n"
"    </node>\n"
"    <node id=\"2\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">2</data>\n"
"      <data key=\"d30\">Global Crossing</data>\n"
"    </node>\n"
"    <node id=\"3\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">3</data>\n"
"      <data key=\"d30\">GEANT</data>\n"
"    </node>\n"
"    <node id=\"4\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">39.20738</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">4</data>\n"
"      <data key=\"d33\">9.13462</data>\n"
"      <data key=\"d30\">CA-1</data>\n"
"    </node>\n"
"    <node id=\"5\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">5</data>\n"
"      <data key=\"d30\">NAMEX</data>\n"
"    </node>\n"
"    <node id=\"6\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">42.35055</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">6</data>\n"
"      <data key=\"d33\">13.39954</data>\n"
"      <data key=\"d30\">AQ-1</data>\n"
"    </node>\n"
"    <node id=\"7\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.72722</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">7</data>\n"
"      <data key=\"d33\">8.56028</data>\n"
"      <data key=\"d30\">SS</data>\n"
"    </node>\n"
"    <node id=\"8\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">38.11582</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">8</data>\n"
"      <data key=\"d33\">13.35976</data>\n"
"      <data key=\"d30\">PA-2</data>\n"
"    </node>\n"
"    <node id=\"9\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.18446</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">9</data>\n"
"      <data key=\"d33\">9.16145</data>\n"
"      <data key=\"d30\">Pv-1</data>\n"
"    </node>\n"
"    <node id=\"10\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.89474</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">10</data>\n"
"      <data key=\"d33\">12.4839</data>\n"
"      <data key=\"d30\">RM-1</data>\n"
"    </node>\n"
"    <node id=\"11\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.09674</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">11</data>\n"
"      <data key=\"d33\">12.38286</data>\n"
"      <data key=\"d30\">PG</data>\n"
"    </node>\n"
"    <node id=\"12\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">38.89079</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">12</data>\n"
"      <data key=\"d33\">16.5987</data>\n"
"      <data key=\"d30\">CZ</data>\n"
"    </node>\n"
"    <node id=\"13\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">13</data>\n"
"      <data key=\"d30\">TIX</data>\n"
"    </node>\n"
"    <node id=\"14\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">44.49381</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">14</data>\n"
"      <data key=\"d33\">11.33875</data>\n"
"      <data key=\"d30\">BO</data>\n"
"    </node>\n"
"    <node id=\"15\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.46427</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">15</data>\n"
"      <data key=\"d33\">9.18951</data>\n"
"      <data key=\"d30\">MI-3</data>\n"
"    </node>\n"
"    <node id=\"16\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">16</data>\n"
"      <data key=\"d30\">VSIX</data>\n"
"    </node>\n"
"    <node id=\"17\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.64861</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">17</data>\n"
"      <data key=\"d33\">13.78</data>\n"
"      <data key=\"d30\">TS-1</data>\n"
"    </node>\n"
"    <node id=\"18\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.83333</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">18</data>\n"
"      <data key=\"d33\">14.25</data>\n"
"      <data key=\"d30\">NA</data>\n"
"    </node>\n"
"    <node id=\"19\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">38.19327</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">19</data>\n"
"      <data key=\"d33\">15.54969</data>\n"
"      <data key=\"d30\">ME</data>\n"
"    </node>\n"
"    <node id=\"20\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">39.30999</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">20</data>\n"
"      <data key=\"d33\">16.25019</data>\n"
"      <data key=\"d30\">CS</data>\n"
"    </node>\n"
"    <node id=\"21\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">37.50213</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">21</data>\n"
"      <data key=\"d33\">15.08719</data>\n"
"      <data key=\"d30\">CT</data>\n"
"    </node>\n"
"    <node id=\"22\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">38.11582</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">22</data>\n"
"      <data key=\"d33\">13.35976</data>\n"
"      <data key=\"d30\">PA</data>\n"
"    </node>\n"
"    <node id=\"23\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">23</data>\n"
"      <data key=\"d30\">EUMED CONNECT</data>\n"
"    </node>\n"
"    <node id=\"24\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">24</data>\n"
"      <data key=\"d30\">MIX</data>\n"
"    </node>\n"
"    <node id=\"25\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">25</data>\n"
"      <data key=\"d30\">Level 3</data>\n"
"    </node>\n"
"    <node id=\"26\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">44.49381</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">26</data>\n"
"      <data key=\"d33\">11.33875</data>\n"
"      <data key=\"d30\">BO-3</data>\n"
"    </node>\n"
"    <node id=\"27\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">27</data>\n"
"      <data key=\"d30\">Cogent</data>\n"
"    </node>\n"
"    <node id=\"28\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">42.04023</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">28</data>\n"
"      <data key=\"d33\">13.4388</data>\n"
"      <data key=\"d30\">FUC</data>\n"
"    </node>\n"
"    <node id=\"29\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.76667</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">29</data>\n"
"      <data key=\"d33\">11.25</data>\n"
"      <data key=\"d30\">FI</data>\n"
"    </node>\n"
"    <node id=\"30\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.76667</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">30</data>\n"
"      <data key=\"d33\">11.25</data>\n"
"      <data key=\"d30\">Fi</data>\n"
"    </node>\n"
"    <node id=\"31\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.41519</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">31</data>\n"
"      <data key=\"d33\">11.88181</data>\n"
"      <data key=\"d30\">PD-2</data>\n"
"    </node>\n"
"    <node id=\"32\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.62773</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">32</data>\n"
"      <data key=\"d33\">17.93682</data>\n"
"      <data key=\"d30\">BR</data>\n"
"    </node>\n"
"    <node id=\"33\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.43861</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">33</data>\n"
"      <data key=\"d33\">12.32667</data>\n"
"      <data key=\"d30\">VE</data>\n"
"    </node>\n"
"    <node id=\"34\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.41519</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">34</data>\n"
"      <data key=\"d33\">11.88181</data>\n"
"      <data key=\"d30\">PD</data>\n"
"    </node>\n"
"    <node id=\"35\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.46427</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">35</data>\n"
"      <data key=\"d33\">9.18951</data>\n"
"      <data key=\"d30\">MI-1</data>\n"
"    </node>\n"
"    <node id=\"36\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">46.06787</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">36</data>\n"
"      <data key=\"d33\">11.12108</data>\n"
"      <data key=\"d30\">TN</data>\n"
"    </node>\n"
"    <node id=\"37\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.46427</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">37</data>\n"
"      <data key=\"d33\">9.18951</data>\n"
"      <data key=\"d30\">MI-2</data>\n"
"    </node>\n"
"    <node id=\"38\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.46427</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">38</data>\n"
"      <data key=\"d33\">9.18951</data>\n"
"      <data key=\"d30\">MI-4</data>\n"
"    </node>\n"
"    <node id=\"39\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">44.40632</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">39</data>\n"
"      <data key=\"d33\">8.93386</data>\n"
"      <data key=\"d30\">GE</data>\n"
"    </node>\n"
"    <node id=\"40\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.07049</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">40</data>\n"
"      <data key=\"d33\">7.68682</data>\n"
"      <data key=\"d30\">TO</data>\n"
"    </node>\n"
"    <node id=\"41\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.67797</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">41</data>\n"
"      <data key=\"d33\">14.76599</data>\n"
"      <data key=\"d30\">SA</data>\n"
"    </node>\n"
"    <node id=\"42\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.64432</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">42</data>\n"
"      <data key=\"d33\">15.80857</data>\n"
"      <data key=\"d30\">PZ</data>\n"
"    </node>\n"
"    <node id=\"43\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.56003</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">43</data>\n"
"      <data key=\"d33\">14.66753</data>\n"
"      <data key=\"d30\">CB</data>\n"
"    </node>\n"
"    <node id=\"44\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.81632</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">44</data>\n"
"      <data key=\"d33\">12.66868</data>\n"
"      <data key=\"d30\">FRA</data>\n"
"    </node>\n"
"    <node id=\"45\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">42.35055</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">45</data>\n"
"      <data key=\"d33\">13.39954</data>\n"
"      <data key=\"d30\">AQ</data>\n"
"    </node>\n"
"    <node id=\"46\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.59816</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">46</data>\n"
"      <data key=\"d33\">13.51008</data>\n"
"      <data key=\"d30\">AN</data>\n"
"    </node>\n"
"    <node id=\"47\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.66852</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">47</data>\n"
"      <data key=\"d33\">16.60158</data>\n"
"      <data key=\"d30\">MT</data>\n"
"    </node>\n"
"    <node id=\"48\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">40.35703</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">48</data>\n"
"      <data key=\"d33\">18.17202</data>\n"
"      <data key=\"d30\">LE</data>\n"
"    </node>\n"
"    <node id=\"49\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.11773</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">49</data>\n"
"      <data key=\"d33\">16.85118</data>\n"
"      <data key=\"d30\">BA</data>\n"
"    </node>\n"
"    <node id=\"50\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.46093</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">50</data>\n"
"      <data key=\"d33\">15.54925</data>\n"
"      <data key=\"d30\">FG</data>\n"
"    </node>\n"
"    <node id=\"51\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">51</data>\n"
"      <data key=\"d30\">Google</data>\n"
"    </node>\n"
"    <node id=\"52\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">52</data>\n"
"      <data key=\"d30\">GEANT</data>\n"
"    </node>\n"
"    <node id=\"53\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.52478</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">53</data>\n"
"      <data key=\"d33\">10.22727</data>\n"
"      <data key=\"d30\">BS</data>\n"
"    </node>\n"
"    <node id=\"54\">\n"
"      <data key=\"d28\">0</data>\n"
"      <data key=\"d29\">54</data>\n"
"      <data key=\"d30\">TO-PIX</data>\n"
"    </node>\n"
"    <node id=\"55\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">41.89474</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">55</data>\n"
"      <data key=\"d33\">12.4839</data>\n"
"      <data key=\"d30\">RM-2</data>\n"
"    </node>\n"
"    <node id=\"56\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.46427</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">56</data>\n"
"      <data key=\"d33\">9.18951</data>\n"
"      <data key=\"d30\">CO</data>\n"
"    </node>\n"
"    <node id=\"57\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">44.82678</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">57</data>\n"
"      <data key=\"d33\">11.62071</data>\n"
"      <data key=\"d30\">Fe</data>\n"
"    </node>\n"
"    <node id=\"58\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">45.18446</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">58</data>\n"
"      <data key=\"d33\">9.16145</data>\n"
"      <data key=\"d30\">Pv</data>\n"
"    </node>\n"
"    <node id=\"59\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.71553</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">59</data>\n"
"      <data key=\"d33\">10.39659</data>\n"
"      <data key=\"d30\">PI</data>\n"
"    </node>\n"
"    <node id=\"60\">\n"
"      <data key=\"d28\">1</data>\n"
"      <data key=\"d31\">43.72621</data>\n"
"      <data key=\"d32\">Italy</data>\n"
"      <data key=\"d29\">60</data>\n"
"      <data key=\"d33\">12.63633</data>\n"
"      <data key=\"d30\">Ur</data>\n"
"    </node>\n"
"    <edge source=\"0\" target=\"35\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre), 10 Gbps</data>\n"
"      <data key=\"d37\">Fibre ottica spenta (Dark Fibre),  </data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"1\" target=\"4\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"2\" target=\"35\">\n"
"      <data key=\"d34\">5</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 5 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">5000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"3\" target=\"37\">\n"
"      <data key=\"d40\">e25</data>\n"
"      <data key=\"d41\">None</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"4\" target=\"10\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"4\" target=\"55\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"4\" target=\"7\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"4\" target=\"7\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"5\" target=\"55\">\n"
"      <data key=\"d34\">13</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 13 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">13000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"6\" target=\"45\">\n"
"      <data key=\"d34\">34</data>\n"
"      <data key=\"d36\">34 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">34000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"6\" target=\"55\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"6\" target=\"55\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"8\" target=\"22\">\n"
"      <data key=\"d40\">e61</data>\n"
"      <data key=\"d42\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"9\" target=\"58\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"9\" target=\"58\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"10\" target=\"44\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"10\" target=\"45\">\n"
"      <data key=\"d34\">622</data>\n"
"      <data key=\"d36\">622 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">622000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"10\" target=\"21\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"10\" target=\"55\">\n"
"      <data key=\"d40\">e9</data>\n"
"      <data key=\"d41\">None</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"10\" target=\"55\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"11\" target=\"55\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"12\" target=\"20\">\n"
"      <data key=\"d34\">100</data>\n"
"      <data key=\"d36\">100 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">100000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"13\" target=\"29\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 1 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"34\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"35\">\n"
"      <data key=\"d40\">e60</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"35\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d36\">10 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"35\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d36\">10 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">2</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"46\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"49\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"55\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d36\">10 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"57\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"57\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"26\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"14\" target=\"29\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"15\" target=\"35\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"15\" target=\"53\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"15\" target=\"37\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"16\" target=\"34\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 1 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"17\" target=\"56\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"17\" target=\"34\">\n"
"      <data key=\"d34\">155</data>\n"
"      <data key=\"d36\">155 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">155000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"41\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"41\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"43\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"43\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"21\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"55\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"18\" target=\"49\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"19\" target=\"21\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"20\" target=\"21\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"21\" target=\"22\">\n"
"      <data key=\"d34\">622</data>\n"
"      <data key=\"d36\">622 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">622000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"21\" target=\"23\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"24\" target=\"37\">\n"
"      <data key=\"d34\">4</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 4Gbps</data>\n"
"      <data key=\"d37\">Peering, </data>\n"
"      <data key=\"d38\">4000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"25\" target=\"37\">\n"
"      <data key=\"d34\">5</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 5 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">5000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"27\" target=\"55\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 10 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"28\" target=\"55\">\n"
"      <data key=\"d34\">34</data>\n"
"      <data key=\"d36\">34 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">34000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"29\" target=\"30\">\n"
"      <data key=\"d34\">34</data>\n"
"      <data key=\"d36\">34 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">34000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"29\" target=\"59\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"31\" target=\"33\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"31\" target=\"33\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"31\" target=\"34\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"31\" target=\"34\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"31\" target=\"34\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">2</data>\n"
"    </edge>\n"
"    <edge source=\"32\" target=\"49\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"32\" target=\"49\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"34\" target=\"35\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"34\" target=\"36\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"35\" target=\"37\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d36\">10 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"35\" target=\"52\">\n"
"      <data key=\"d34\">20</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre), 20 Gbps</data>\n"
"      <data key=\"d37\">Fibre ottica spenta (Dark Fibre),  </data>\n"
"      <data key=\"d38\">20000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"35\" target=\"56\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"36\" target=\"37\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"51\">\n"
"      <data key=\"d34\">2</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 2 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">2000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"38\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"39\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"40\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"56\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"55\">\n"
"      <data key=\"d34\">10</data>\n"
"      <data key=\"d36\">10 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">10000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"58\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"37\" target=\"58\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">1</data>\n"
"    </edge>\n"
"    <edge source=\"38\" target=\"56\">\n"
"      <data key=\"d36\">Fibre ottica spenta (Dark Fibre)</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"39\" target=\"59\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"40\" target=\"59\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"40\" target=\"54\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d36\">Peering, 1 Gbps</data>\n"
"      <data key=\"d37\">Peering,  </data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"42\" target=\"49\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"44\" target=\"55\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"46\" target=\"60\">\n"
"      <data key=\"d34\">622</data>\n"
"      <data key=\"d36\">622 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">622000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"47\" target=\"49\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"48\" target=\"49\">\n"
"      <data key=\"d34\">1</data>\n"
"      <data key=\"d36\">1 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">1000000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"49\" target=\"50\">\n"
"      <data key=\"d34\">155</data>\n"
"      <data key=\"d36\">155 Mbps</data>\n"
"      <data key=\"d35\">M</data>\n"
"      <data key=\"d38\">155000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"    <edge source=\"55\" target=\"59\">\n"
"      <data key=\"d34\">2.5</data>\n"
"      <data key=\"d36\">2.5 Gbps</data>\n"
"      <data key=\"d35\">G</data>\n"
"      <data key=\"d38\">2500000000.0</data>\n"
"      <data key=\"d39\">0</data>\n"
"    </edge>\n"
"  </graph>\n"
"</graphml>\n";
  // clang-format on
}

} // namespace qr
} // namespace uiiit
